<Project Sdk="Uno.Sdk">
  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <TargetFrameworks>net10.0-desktop;net10.0-windows10.0.26100.0</TargetFrameworks>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <TargetFrameworks>net10.0-desktop</TargetFrameworks>
    <!-- net10.0-android;net10.0-ios;net10.0-browserwasm; -->
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>
    <PublishAot>true</PublishAot>

    <!-- Display name -->
    <ApplicationTitle>UnoVibe</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.unovibe</ApplicationId>

    <!-- Package Publisher -->
    <ApplicationPublisher>UnoVibe</ApplicationPublisher>
    <!-- Package Description -->
    <Description>UnoVibe powered by Uno Platform.</Description>
    <UnoIconForegroundFile>Assets/Icons/UnoVibe.png</UnoIconForegroundFile>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0-windows' ">
    <PackageReference Include="QuickMarkup.WinUI" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'net10.0-windows' ">
    <PackageReference Include="QuickMarkup.Uno" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Automatically emit generated files for every project build -->
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

</Project>
