namespace UnoVibe.Integration;

/// <summary>
/// Source-generated System.Text.Json context covering every type the app (de)serializes.
/// Required for native AOT: reflection-based JSON (de)serialization is unavailable when
/// trimming/AOT compiling, so all <c>JsonSerializer</c> and <c>PostAsJsonAsync</c>/<c>PatchAsJsonAsync</c>
/// call sites must route through <see cref="Default"/>.
/// </summary>
[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, WriteIndented = false)]
[JsonSerializable(typeof(SessionInfo))]
[JsonSerializable(typeof(SessionModelInfo))]
[JsonSerializable(typeof(SessionTimeInfo))]
[JsonSerializable(typeof(SessionTokensInfo))]
[JsonSerializable(typeof(SessionCacheInfo))]
[JsonSerializable(typeof(List<SessionInfo>))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(CreateSessionModelRequest))]
[JsonSerializable(typeof(SendPromptRequest))]
[JsonSerializable(typeof(PromptPart))]
[JsonSerializable(typeof(SendPromptModelRequest))]
[JsonSerializable(typeof(SendCommandRequest))]
[JsonSerializable(typeof(SendShellRequest))]
[JsonSerializable(typeof(UpdateSessionTitleRequest))]
[JsonSerializable(typeof(EmptyRequest))]
[JsonSerializable(typeof(RevertRequest))]
[JsonSerializable(typeof(ForkSessionRequest))]
[JsonSerializable(typeof(ReplyQuestionRequest))]
[JsonSerializable(typeof(ReplyPermissionRequest))]
[JsonSerializable(typeof(AuthSetRequest))]
[JsonSerializable(typeof(OAuthAuthorizeRequest))]
[JsonSerializable(typeof(OAuthCallbackRequest))]
[JsonSerializable(typeof(OAuthAuthorization))]
[JsonSerializable(typeof(ProviderListResult))]
[JsonSerializable(typeof(ProviderInfo))]
[JsonSerializable(typeof(ProviderModelInfo))]
[JsonSerializable(typeof(ModelLimitInfo))]
[JsonSerializable(typeof(ProviderAuthMethod))]
[JsonSerializable(typeof(AuthPrompt))]
[JsonSerializable(typeof(AuthPromptOption))]
[JsonSerializable(typeof(AuthWhen))]
[JsonSerializable(typeof(PermissionRequestItem))]
[JsonSerializable(typeof(PermissionToolInfo))]
[JsonSerializable(typeof(List<PermissionRequestItem>))]
[JsonSerializable(typeof(SessionStatusInfo))]
[JsonSerializable(typeof(SessionStatusActionInfo))]
[JsonSerializable(typeof(VcsInfo))]
[JsonSerializable(typeof(PathInfo))]
[JsonSerializable(typeof(AgentInfo))]
[JsonSerializable(typeof(CommandInfo))]
[JsonSerializable(typeof(SkillInfo))]
[JsonSerializable(typeof(McpStatusInfo))]
[JsonSerializable(typeof(QuestionRequest))]
[JsonSerializable(typeof(QuestionInfo))]
[JsonSerializable(typeof(QuestionOption))]
[JsonSerializable(typeof(QuestionToolInfo))]
[JsonSerializable(typeof(MessageWithParts))]
[JsonSerializable(typeof(List<MessageWithParts>))]
[JsonSerializable(typeof(List<AgentInfo>))]
[JsonSerializable(typeof(List<CommandInfo>))]
[JsonSerializable(typeof(List<SkillInfo>))]
[JsonSerializable(typeof(List<CommandInfo>))]
[JsonSerializable(typeof(List<QuestionRequest>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(Dictionary<string, SessionStatusInfo>))]
[JsonSerializable(typeof(Dictionary<string, McpStatusInfo>))]
[JsonSerializable(typeof(Dictionary<string, ProviderAuthMethod[]>))]
internal sealed partial class AppJsonContext : JsonSerializerContext
{
}
